## TCRAFT oligo test run
Create a script that is able to convert the different headers into a input .csv formatted for TCRAFT pipeline.

In [ ]:
import sys
sys.path.insert(0, "..")

import pandas as pd
from config import ALL_DATA_DIR

sample_df = pd.read_csv(ALL_DATA_DIR / "Sample_TCR_List.csv")
AS_top_96 = pd.read_csv(ALL_DATA_DIR / "AS_Top_96_TCRs.csv")
positive_ctrls = pd.read_csv(ALL_DATA_DIR / "Positive_Ctrl_TCRs.csv")

In [ ]:
# load csvs
AS_df = pd.read_csv(ALL_DATA_DIR / "AS_Top_96_TCRs.csv")
Ctrl_df = pd.read_csv(ALL_DATA_DIR / "Positive_Ctrl_TCRs.csv")

combined = pd.concat([AS_df, Ctrl_df], ignore_index=True)
combined

In [3]:
test_df = combined.copy()

column_map = {
        "CLONE_ID": "Name",
        "va": "V_alpha",
        "vb": "V_beta",
        "cdr3a": "CDR3_alpha",
        "cdr3b": "CDR3_beta",
        "ja": "J_alpha",
        "jb": "J_beta",
    }

test_df = test_df.rename(columns=column_map)
test_df

,V_alpha,J_alpha,CDR3_alpha,V_beta,J_beta,CDR3_beta,Name,nndists_tcr,clusters_tcr_names,Name,V_alpha,V_beta,CDR3_alpha,CDR3_beta,J_alpha,J_beta,Epitope,HLA-class
0,TRAV1-2,TRAJ9,CAFWAGGFKTIF,TRBV6-2,TRBJ1-2,CASSYGDISYGYTF,AS_Clone0319,96.600000,10_AV1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TRAV12-2,TRAJ41,CAVNIHSGYALNF,TRBV28,TRBJ2-1,CASSLLAGGNNEQFF,AS_Clone0819,31.866667,100_AV12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TRAV12-2,TRAJ8,CAAAEGNTGFQKLVF,TRBV28,TRBJ1-5,CASSLWTAGDNQPQHF,AS_Clone0907,134.000000,100_AV12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TRAV29/DV5,TRAJ52,CAASAFMSSYGKLTF,TRBV3-1,TRBJ2-7,CASSQEPGTSTYEQYF,AS_Clone3389,110.777778,103_bv4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TRAV13-1,TRAJ6,CAASIRGGSYIPTF,TRBV6-1,TRBJ2-3,CASSASGSTDTQYF,AS_Clone1222,113.266667,108_AV13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,TRAV26-2,TRAJ23,CILRGSYNQGGKLIF,TRBV29-1,TRBJ1-1,CSVELGTVLTGANTEAFF,AS_Clone2977,227.711111,15_BV29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,TRAV8-6,TRAJ50,CAVSGSLETSYDKVIF,TRBV29-1,TRBJ2-7,CSVRVEGYEQYF,AS_Clone5095,181.622222,15_BV29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gp100,TRAV21,TRBV7-3,CAVLSSGGSNYKLTF,CASSFIGGTDTQYF,TRAJ53,TRBJ2-3,YLEPGPVTA,HLA-A*02
97,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gp100,TRAV17,TRBV19*01,CATDGDTPLVF,CASSIGGPYEQYF,TRAJ29,TRBJ2-7*01,YLEPGPVTA,HLA-A*02
98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MART-1,TRAV12-2,TRBV6-4,CAVNFGGGKLIF,CASSLSFGTEAFF,TRAJ23*02,TRBJ1-1,ELAGIGILTV,HLA-A*02

In [4]:
def standardize_to_sample_format(df, select=None):
    """Convert a df in AS_top_96 or positive_ctrls format into sample_df format.

    select: optionally, an integer number of TCRs to randomly select from the result.
    """
    df = df.copy()
    df.columns = df.columns.str.replace("﻿", "", regex=False).str.strip()

    # AS_top_96 uses short lowercase column names; rename to sample_df's convention.
    # positive_ctrls already uses sample_df's column names (plus extra columns).
    column_map = {
        "CLONE_ID": "Name",
        "va": "V_alpha",
        "vb": "V_beta",
        "cdr3a": "CDR3_alpha",
        "cdr3b": "CDR3_beta",
        "ja": "J_alpha",
        "jb": "J_beta",
    }
    df = df.rename(columns=column_map)

    sample_cols = ["Name", "V_alpha", "V_beta", "CDR3_alpha", "CDR3_beta", "J_alpha", "J_beta"]
    df = df[sample_cols].dropna(how="all").reset_index(drop=True)

    if select is not None:
        df = df.sample(n=select).reset_index(drop=True)

    return df

In [6]:
test_2 = standardize_to_sample_format(test_df)
test_2

,Name,Name,V_alpha,V_alpha,V_beta,V_beta,CDR3_alpha,CDR3_alpha,CDR3_beta,CDR3_beta,J_alpha,J_alpha,J_beta,J_beta
0,AS_Clone0319,NaN,TRAV1-2,NaN,TRBV6-2,NaN,CAFWAGGFKTIF,NaN,CASSYGDISYGYTF,NaN,TRAJ9,NaN,TRBJ1-2,NaN
1,AS_Clone0819,NaN,TRAV12-2,NaN,TRBV28,NaN,CAVNIHSGYALNF,NaN,CASSLLAGGNNEQFF,NaN,TRAJ41,NaN,TRBJ2-1,NaN
2,AS_Clone0907,NaN,TRAV12-2,NaN,TRBV28,NaN,CAAAEGNTGFQKLVF,NaN,CASSLWTAGDNQPQHF,NaN,TRAJ8,NaN,TRBJ1-5,NaN
3,AS_Clone3389,NaN,TRAV29/DV5,NaN,TRBV3-1,NaN,CAASAFMSSYGKLTF,NaN,CASSQEPGTSTYEQYF,NaN,TRAJ52,NaN,TRBJ2-7,NaN
4,AS_Clone1222,NaN,TRAV13-1,NaN,TRBV6-1,NaN,CAASIRGGSYIPTF,NaN,CASSASGSTDTQYF,NaN,TRAJ6,NaN,TRBJ2-3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,AS_Clone2977,NaN,TRAV26-2,NaN,TRBV29-1,NaN,CILRGSYNQGGKLIF,NaN,CSVELGTVLTGANTEAFF,NaN,TRAJ23,NaN,TRBJ1-1,NaN
95,AS_Clone5095,NaN,TRAV8-6,NaN,TRBV29-1,NaN,CAVSGSLETSYDKVIF,NaN,CSVRVEGYEQYF,NaN,TRAJ50,NaN,TRBJ2-7,NaN
96,NaN,gp100,NaN,TRAV21,NaN,TRBV7-3,NaN,CAVLSSGGSNYKLTF,NaN,CASSFIGGTDTQYF,NaN,TRAJ53,NaN,TRBJ2-3
97,NaN,gp100,NaN,TRAV17,NaN,TRBV19*01,NaN,CATDGDTPLVF,NaN,CASSIGGPYEQYF,NaN,TRAJ29,NaN,TRBJ2-7*01
98,NaN,MART-1,NaN,TRAV12-2,NaN,TRBV6-4,NaN,CAVNFGGGKLIF,NaN,CASSLSFGTEAFF,NaN,TRAJ23*02,NaN,TRBJ1-1

In [ ]:
TCRAFT_96 = standardize_to_sample_format(AS_top_96, select=93)
len(TCRAFT_96)
# save csv
TCRAFT_96.to_csv(ALL_DATA_DIR / "01_AS_TCRAFT_96.csv")

In [ ]:
# generate oligos from aa sequence
from TCRAFT.Generate import generate_cdr3_oligos

generate_cdr3_oligos(
    input_csv_path= str(ALL_DATA_DIR / "01_AS_TCRAFT_96.csv"),
    output_dir= ALL_DATA_DIR / "01_oligos_AS_TCRAFT_96",
    name_col="Name"
)

In [ ]:
# validate oligos by simulating Golden Gate
from TCRAFT.Validate import validate_cdr3_oligos

validate_cdr3_oligos(input_csv_path=str(ALL_DATA_DIR / "01_oligos_AS_TCRAFT_96" / "All_93_CDR3_oligos.csv"),
                     output_dir=str(ALL_DATA_DIR/"01_validation_AS_TCRAFT_96"))

In [ ]:
# select sequences 

CDR3_oligos = pd.read_csv(ALL_DATA_DIR / "01_oligos_AS_TCRAFT_96" / "All_93_CDR3_oligos.csv")
CDR3_oligos.columns

# categorize by pool
pool_A_CDR3 = CDR3_oligos[CDR3_oligos['Pool'] == "A"]
pool_B_CDR3 = CDR3_oligos[CDR3_oligos['Pool'] == "B"]

In [ ]:
# write new csv
## pool A
CDR3_oligos_to_order = pool_A_CDR3['Sequence']
CDR3_oligos_to_order.to_csv(ALL_DATA_DIR / "01_PoolA_IDT_oligos.csv")

## pool B
CDR3_oligos_to_order = pool_B_CDR3['Sequence']
CDR3_oligos_to_order.to_csv(ALL_DATA_DIR / "01_PoolB_IDT_oligos.csv")

In [ ]:
import generate_TCRAFT_oligopool as gt

df = pd.read_csv(ALL_DATA_DIR / "01_AS_TCRAFT_96.csv")

AS_cdr3 = gt.standardize_to_sample_format(
    df=df,
    select=93,
    output_dir=(ALL_DATA_DIR / "test")
)

In [ ]:
gt.generate_oligos(
    tcraft_csv=ALL_DATA_DIR / "test" / "standardized_TCRs.csv",
    prefix="02",
    name="oligos_test_run",
    data_dir=ALL_DATA_DIR / "test"
)

In [ ]:
gt.validate_oligos(
    oligos_csv=ALL_DATA_DIR/"test"/"02_oligos_test_run"/"All_93_CDR3_oligos.csv",
    prefix="02",
    name="test_run",
    data_dir=ALL_DATA_DIR / "test"
)

In [ ]:
gt.select_sequences_by_pool(
    oligos_csv=ALL_DATA_DIR/"test"/"02_oligos_test_run"/"All_93_CDR3_oligos.csv",
    prefix="02",
    data_dir=ALL_DATA_DIR / "test"
)

In [ ]:
import sys, importlib.util, subprocess
print("executable:", sys.executable)
print("prefix:", sys.prefix)
print("version:", sys.version)
print("--- spec ---")
for name in ["TCRAFT", "tcraft"]:
    try:
        s = importlib.util.find_spec(name)
    except Exception as e:
        s = f"ERR {e}"
    print(name, "->", s)